name: previsecours
title: Previsecours
email: contact@previsecours.fr
description: |
  P
baseurl: ""
url: "https://www.previsecours.fr"

authors:
  tiphaine:
    name: Tiphane Phe Neau
    linkedin: pheneau
    twitter: datatiph
    image: /assets/images/TiphainePheNeau.png
    text: Tiphaine est titulaire d’un doctorat en informatique de l’Université Pierre et Marie Curie. Après ses études, elle a voulu utiliser ses capacités d’abstraction, d’observation et de réalisation pour s’attaquer à de nouvelles problématiques en tant que data scientist. Elle a travaillé dans des entreprises telles que Dailymotion, Clustree ou Saegus sur une grande variété de sujets. En tant que data scientist, elle apprécie combiner les connaissances métiers avec les aspects techniques pour obtenir des solutions efficaces et réalistes.
  guillaume:
    name: Guillaume Lancrenon 
    linkedin: guillaumelancrenon
    image: /assets/images/GuillaumeLancrenon.png
    text: Guillaume Lancrenon a débuté comme ingénieur d’exploration sismique chez Westerngeco, une filiale offshore de Schlumberger. Il est ensuite passé par l’entreprenariat avec la réalisation de CommoPrices, une startup spécialisée dans le suivi du cours des matières premières. Il a récemment rejoint le programme EIG pour mettre ses compétences au service des pompiers.
  daniel:
    name: Daniel Ansellem
    image: /assets/images/ansellem.JPG
    text: "Daniel Ansellem a été nommé en Juillet 2016 Administrateur ministériel des données du Ministère de l’Intérieur, il dirige également depuis cette date la mission de coordination et d’appui à la valorisation des données, au sein de la Mission de gouvernance ministérielle des SIC.

« Je suis convaincu que les données contenues dans les centaines d’applications du Ministère de l’Intérieur constituent une richesse à exploiter, pour davantage d’efficacité et de transparence.  Il faut faire la preuve, par l’expérimentation, que l’on peut, en moins d’un an, construire un outil fonctionnel permettant de mieux utiliser certaines données, par l’enrichissement, le croisement, la visualisation, ou la montée en qualité. Le dispositif EIG permet de répondre à cet objectif en dédiant deux ingénieurs de haut niveau à un défi qui correspond à leurs compétences, au sein d’une structure transverse, où ils bénéficient d’une large autonomie, mais aussi d’un tutorat et d’outils adaptés. »"
project:
  general:
    name: matchID
    repo: matchID-project
  backend:
    name: Backend
    repo: matchID-project/backend
    download: "https://github.com/matchID-project/backend/archive/master.zip"
  frontend:
    name: Frontend
    repo: matchID-project/frontend
    download: "https://github.com/matchID-project/frontend/archive/master.zip"
  examples:
    name: Examples
    repo: matchID-project/examples
    download: "https://github.com/matchID-project/examples/archive/master.zip"
github_url: "https://github.com/"
linkedin_url : "https://linkedin.com/in/"
twitter_url : "https://twitter.com/"

# Build settings
github: [metadata]
theme: minima
markdown: kramdown
plugins:

# sass:
#   style: compressed
#   sass_dir: _sass


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
